### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by fkeusch** [spatie/npm-install-peers#1]
Does not work? I get this syntax error when executing npm-install-peers

$ npm-install-peers

C:\Program Files\nodejs\node_modules\npm-install-peers\index.js:4
const chalk = require('chalk')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by sebastiandedeyne** [comment]
What node version are you on?

**Comment by fkeusch** [comment]
v0.10.30 . seems to be old. I'll try to update this. Thanks
